# Source language and JDK version to use
language: java
jdk: oraclejdk7

# Compile and package JAR and set build properties
install: mvn dependency:go-offline
script: mvn package -DbuildNumber=$TRAVIS_BUILD_NUMBER -DciSystem=travis -Dcommit=${TRAVIS_COMMIT:0:7}

# Perform steps after compilation/test success
after_success:
  # Get files for use with build, namely the custom Maven settings.xml and scripts
  - "git clone https://github.com/flow/travis-ci-resources.git $HOME/build/flow/travis"
  # SNAPSHOTS: Check if commit is not a pull request, if repo is official, if branch is not master; then generate, sign, and deploy artifacts and reports
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == flow/math ]] && [[ $TRAVIS_BRANCH != master ]] && mvn javadoc:jar source:jar cobertura:cobertura coveralls:report -DserviceJobId=$TRAVIS_JOB_ID deploy --settings $HOME/build/flow/travis/settings.xml"
  # RELEASES: Check if commit is not a pull request, if repo is official, if branch is master; then run deployment script
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == flow/math ]] && [[ $TRAVIS_BRANCH == master ]] && $HOME/build/flow/travis/deploy.sh"

# RELEASES: Deploy main JAR to GitHub Releases
deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file: "target/flow-math-`cat version.txt`.jar"
  skip_cleanup: true
  on:
    branch: master

# Notification services
notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false
  webhooks:
    # Send build information and status to Notifico
    - http://n.tkte.ch/h/2049/2uvlIumWlN12D5GMEdCWxXB-

# Environmental system variables
env:
  global:
    # Make the log output cleaner
    - TERM=dumb
    # Super secure, encrypted variables! Ssssh!
    - secure: "YhnCvshzsTFTbQwNmrMsnAtxM92ZGXyTtIZycdEukYJC8mo46irxTBS48oc271xL6bRdt4VCnw3S8kS9d9RbW+tsbHuolF/T6TM65b1q8rIKG0JECKdDi52UR2P4yEbi+EMYbVymCHOlWn9zteZNwMvpme1ERyuphvSSd1N0NNw="
    - secure: "HGKAJKPtz2nazfY4IwaVj8AfkD5algQsG7QMr0kT1y6CKKoVWyYl4rIdHRnkXt7x7IJ4c5hASG//ozGCkFAmnwZWmusWaS4nqcvvV5xfUUpx/ucKoIpV59m/K9hIC968P4KfloSy2toYYigONyHnKDuCaWNvFJOnJ0M3CMShZEU="
    - secure: "AMV2j4og2o1VcXhCkjvhZIUKbmS/I41FvVst3mrujYBJ4FCadgSLBPzlpTT/JljTtZJizNO4lDfY6zUwC2S5bOhm3X/hbgod5UN1FQYWBmBoB2Eb59U8UUuDyLCQKSWblbLxrCMuDjG7t31mAtwaublntOWGbkiYclTV1CjMtL4="
    - secure: "rgTp8cSPFTFyS2DojvCicdcnROeTLYwJMFtAIpd/aFeeeA9iM+S2+uHoT1iaAynclBL29IU5YlejUv+acMRvaEl2pzddOjuVAX49RqElEgG6hi0u6B5g3h56xZucZeqGo4mREaOrvFhL1IxxuK/0dX2sS/MnyDSwwk5ooPpAikQ="
